SELECT
    p_item.AS_OF_DATE,
    p_item.ITEM_HK,
    link.CATEGORY_HK,
    
    -- Fetch attributes from the Satellites via the PIT lookup
    sat_item.ITEM_DESCRIPTION, 
    sat_cat.CATEGORY_NAME

FROM {{ ref('pit_item') }} p_item

-- Join the Link
JOIN {{ ref('LINK_ITEM_CATEGORIES') }} link
    ON link.ITEM_HK = p_item.ITEM_HK

-- Join the Category PIT (on matching keys AND matching As-Of-Date)
JOIN {{ ref('pit_categories') }} p_cat
    ON p_cat.CATEGORY_HK = link.CATEGORY_HK
    AND p_cat.AS_OF_DATE = p_item.AS_OF_DATE

-- Join the actual Satellites to get descriptive data
JOIN {{ ref('satellite_items') }} sat_item
    ON sat_item.ITEM_HK = p_item.ITEM_HK
    AND sat_item.SALES_DATE = p_item.SATELLITE_ITEMS_LDTS -- Generated by the macro

JOIN {{ ref('satellite_categories') }} sat_cat
    ON sat_cat.CATEGORY_HK = p_cat.CATEGORY_HK
    AND sat_cat.SALES_DATE = p_cat.SATELLITE_CATEGORIES_LDTS -- Generated by the macro